// Chess interludes for the hall screen. Each lesson is a start position plus a list of steps.
// A step moves pieces with `ops` ([from, to] squares; a piece already on `to` is captured) and shows a caption.
// Pieces: uppercase = White (K Q R B N P), lowercase = Black. `hold` is how long the step stays on screen (ms).
// Keep every line legal and checked by hand: this goes in front of 90 chess families.
window.LESSONS = [
  {
    id: 'opera',
    title: 'The Opera Game',
    subtitle: 'Paul Morphy v Duke Karl and Count Isouard · Paris, 1858',
    blurb: 'Played in a box at the opera. Morphy, with White, gives up piece after piece to get his pieces out faster than his opponents, then mates in 17 moves. The most quoted game ever played.',
    start: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR',
    steps: [
      { san: '1. e4', ops: [['e2', 'e4']], note: 'White takes the centre.' },
      { san: '1… e5', ops: [['e7', 'e5']] },
      { san: '2. Nf3', ops: [['g1', 'f3']], note: 'Knights before bishops, and the knight attacks e5.' },
      { san: '2… d6', ops: [['d7', 'd6']] },
      { san: '3. d4', ops: [['d2', 'd4']], note: 'A second pawn hits the centre.' },
      { san: '3… Bg4', ops: [['c8', 'g4']], note: 'Black pins the knight to the queen. Morphy does not mind.' },
      { san: '4. dxe5', ops: [['d4', 'e5']] },
      { san: '4… Bxf3', ops: [['g4', 'f3']] },
      { san: '5. Qxf3', ops: [['d1', 'f3']], note: 'White has a bishop and queen out already. Black has nothing developed.' },
      { san: '5… dxe5', ops: [['d6', 'e5']] },
      { san: '6. Bc4', ops: [['f1', 'c4']], note: 'Bishop and queen both aim at f7, the weakest square on the board.' },
      { san: '6… Nf6', ops: [['g8', 'f6']] },
      { san: '7. Qb3', ops: [['f3', 'b3']], note: 'Now f7 and b7 are both attacked.' },
      { san: '7… Qe7', ops: [['d8', 'e7']], note: 'The queen defends f7 but blocks her own bishop in.' },
      { san: '8. Nc3', ops: [['b1', 'c3']], note: 'Morphy could take on b7 and win a pawn. He develops instead.' },
      { san: '8… c6', ops: [['c7', 'c6']] },
      { san: '9. Bg5', ops: [['c1', 'g5']], note: 'Every White piece is out. Black still has three at home.' },
      { san: '9… b5', ops: [['b7', 'b5']], note: 'Black tries to push the bishop away.' },
      { san: '10. Nxb5!', ops: [['c3', 'b5']], note: 'A knight for a pawn. The point is the file it opens.', hold: 5500 },
      { san: '10… cxb5', ops: [['c6', 'b5']] },
      { san: '11. Bxb5+', ops: [['c4', 'b5']], note: 'Check. The knight must block.' },
      { san: '11… Nbd7', ops: [['b8', 'd7']] },
      { san: '12. O-O-O', ops: [['e1', 'c1'], ['a1', 'd1']], note: 'Castles long: the king goes safe and the rook lands on the open d-file, aiming at the pinned knight.', hold: 6000 },
      { san: '12… Rd8', ops: [['a8', 'd8']], note: 'Black defends the knight.' },
      { san: '13. Rxd7!', ops: [['d1', 'd7']], note: 'A rook for a knight. The second sacrifice.', hold: 5500 },
      { san: '13… Rxd7', ops: [['d8', 'd7']] },
      { san: '14. Rd1', ops: [['h1', 'd1']], note: 'The other rook takes over the file. Everything is pinned.' },
      { san: '14… Qe6', ops: [['e7', 'e6']], note: 'Black offers to trade queens. Morphy has seen further.' },
      { san: '15. Bxd7+', ops: [['b5', 'd7']] },
      { san: '15… Nxd7', ops: [['f6', 'd7']] },
      { san: '16. Qb8+!!', ops: [['b3', 'b8']], note: 'The queen is given away. The knight has to take.', hold: 6000 },
      { san: '16… Nxb8', ops: [['d7', 'b8']] },
      { san: '17. Rd8#', ops: [['d1', 'd8']], note: 'Checkmate. The rook is guarded by the bishop on g5, and the king has nowhere to go.', hold: 9000 },
    ],
    outro: 'Three sacrifices, a knight, a rook and a queen, and every White piece took part. Get your pieces out, then look for the open file.',
  },
  {
    id: 'smothered',
    title: 'Smothered mate',
    subtitle: 'Philidor\'s legacy · a pattern every player should know',
    blurb: 'A lone knight delivers checkmate because the king is hemmed in by its own pieces. The queen is sacrificed to make it happen.',
    start: '5rk1/5ppp/8/6N1/8/2Q5/5PPP/6K1',
    steps: [
      { san: 'The position', ops: [], note: 'White: queen c3, knight g5. Black\'s king on g8 is surrounded by its own rook and pawns.', hold: 6000 },
      { san: '1. Qc4+', ops: [['c3', 'c4']], note: 'Check along the diagonal. The king must step into the corner.', hold: 5000 },
      { san: '1… Kh8', ops: [['g8', 'h8']] },
      { san: '2. Nf7+', ops: [['g5', 'f7']], note: 'Knight check. The king comes back out.' },
      { san: '2… Kg8', ops: [['h8', 'g8']] },
      { san: '3. Nh6+', ops: [['f7', 'h6']], note: 'Double check: knight and queen at once. The only answer is to move the king.', hold: 5500 },
      { san: '3… Kh8', ops: [['g8', 'h8']] },
      { san: '4. Qg8+!!', ops: [['c4', 'g8']], note: 'The queen goes right next to the king. The rook has to take her.', hold: 6000 },
      { san: '4… Rxg8', ops: [['f8', 'g8']] },
      { san: '5. Nf7#', ops: [['h6', 'f7']], note: 'Checkmate. The king cannot move: its own rook and pawns fill every square.', hold: 9000 },
    ],
    outro: 'Queen check, knight check, double check, queen sacrifice, knight mate. Look for it whenever a king is boxed in by its own pieces.',
  },
  {
    id: 'twobishops',
    title: 'Two bishops checkmate',
    subtitle: 'The finishing net',
    blurb: 'Two bishops side by side control two whole diagonals. With the king\'s help they drive the enemy king into a corner and mate it there.',
    start: '6k1/8/5K2/4B3/B7/8/8/8',
    steps: [
      { san: 'The position', ops: [], note: 'White: king f6, bishops a4 and e5. Black\'s king is already near the corner.', hold: 6000 },
      { san: '1. Kg6', ops: [['f6', 'g6']], note: 'The king takes away f7, g7 and h7. The corner is now the only place to go.', hold: 5000 },
      { san: '1… Kf8', ops: [['g8', 'f8']], note: 'h8 is covered by the dark bishop, so the king goes the other way.' },
      { san: '2. Bd6+', ops: [['e5', 'd6']], note: 'Check. e8 is covered by the light bishop, so back to g8.', hold: 5000 },
      { san: '2… Kg8', ops: [['f8', 'g8']] },
      { san: '3. Bb3+', ops: [['a4', 'b3']], note: 'Check from the other bishop. Only the corner is left.', hold: 5000 },
      { san: '3… Kh8', ops: [['g8', 'h8']] },
      { san: '4. Be5#', ops: [['d6', 'e5']], note: 'Checkmate. One bishop checks along the long diagonal, the other covers g8, the king covers g7 and h7.', hold: 9000 },
    ],
    outro: 'Keep the bishops next to each other, bring your king up, and push the enemy king into a corner of either colour.',
  },
  {
    id: 'backrank',
    title: 'Back-rank mate',
    subtitle: 'Why a king needs a hole to breathe',
    blurb: 'Three pawns in front of the king feel safe. They are a prison if the back rank is left unguarded.',
    start: '2r3k1/5ppp/8/8/4Q3/8/5PPP/4R1K1',
    steps: [
      { san: 'The position', ops: [], note: 'Both kings sit behind three pawns. White has a queen and rook on open files. Black\'s rook guards the back rank, but only just.', hold: 7000 },
      { san: '1. Qe8+!', ops: [['e4', 'e8']], note: 'The queen walks into the rook. Black must take: the king cannot.', hold: 6000 },
      { san: '1… Rxe8', ops: [['c8', 'e8']] },
      { san: '2. Rxe8#', ops: [['e1', 'e8']], note: 'Checkmate. The pawns on f7, g7 and h7 block every escape.', hold: 9000 },
    ],
    outro: 'Before the endgame, give your king an escape square: push the h-pawn one step. And look for the same trick against your opponent.',
  },
  {
    id: 'scholars',
    title: 'Scholar\'s mate, and how to stop it',
    subtitle: 'The four-move trap',
    blurb: 'The queen and bishop both attack f7. Many young players lose to this once. Nobody should lose to it twice.',
    start: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR',
    steps: [
      { san: '1. e4', ops: [['e2', 'e4']] },
      { san: '1… e5', ops: [['e7', 'e5']] },
      { san: '2. Bc4', ops: [['f1', 'c4']], note: 'The bishop looks at f7.' },
      { san: '2… Nc6', ops: [['b8', 'c6']] },
      { san: '3. Qh5', ops: [['d1', 'h5']], note: 'The queen also looks at f7. Two attackers, one defender: the king.', hold: 5500 },
      { san: '3… Nf6??', ops: [['g8', 'f6']], note: 'The natural move, attacking the queen. It loses at once.', hold: 5000 },
      { san: '4. Qxf7#', ops: [['h5', 'f7']], note: 'Checkmate. The bishop guards the queen, so the king cannot take.', hold: 7000 },
      { san: 'Rewind', ops: [], position: 'r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR', note: 'Back to move 3. Black to play. What stops it?', hold: 5000 },
      { san: '3… g6!', ops: [['g7', 'g6']], note: 'The pawn attacks the queen and blocks the diagonal to f7. Also good: 3… Qe7, guarding f7 directly.', hold: 7000 },
      { san: '4. Qf3', ops: [['h5', 'f3']], note: 'The queen tries again from f3.' },
      { san: '4… Nf6', ops: [['g8', 'f6']], note: 'Now the knight blocks the queen. f7 is safe, and White has wasted three queen moves.', hold: 8000 },
    ],
    outro: 'If a queen comes out early, ask what it attacks. Block or defend f7 with a pawn or a knight, then get your pieces out while the queen wastes time.',
  },
  {
    id: 'fork',
    title: 'The knight fork',
    subtitle: 'One move, two targets',
    blurb: 'A knight attacks up to eight squares at once, and it is the only piece that can attack a queen without being attacked back.',
    start: 'r3k3/8/4N3/8/8/8/8/6K1',
    steps: [
      { san: 'The position', ops: [], note: 'White knight on e6. Black has a king on e8 and a rook on a8.', hold: 5500 },
      { san: '1. Nc7+', ops: [['e6', 'c7']], note: 'Check! From c7 the knight also attacks the rook on a8. A royal fork.', hold: 6000 },
      { san: '1… Kd7', ops: [['e8', 'd7']], note: 'The king must move. The rook is left behind.' },
      { san: '2. Nxa8', ops: [['c7', 'a8']], note: 'The knight wins a whole rook.', hold: 7000 },
    ],
    outro: 'Before every move, look at where your knight could land next. If two enemy pieces sit a knight\'s jump from the same square, you may have a fork.',
  },
];
